name: build
on:
  workflow_dispatch:
jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Test
      run: go test -race ./...

    - name: Lint
      run: "go vet ./..."

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.2"
        install-go: false

    - name: Build
      run: go build ./...
